### ISSUE TITLE
docker-compose race condition - elasticsearch not ready

### ISSUE THREAD

**Issue by phearnix** [covoiturage-libre/covoiturage-libre#359]
When using ```docker-compose up``` I get the error ```Faraday::ConnectionFailed: Couldn't connect to server```

Adding an extra 25 seconds to the delay solves my issue.

sleep is now 30

```
web:
    build:
      context: .
    command: bash -c "./wait-for-it.sh db:5432 elasticsearch:9200 redis:6379 -- bundle exec rake db:migrate && sleep 30 && bundle exec rake searchkick:reindex CLASS=City && bundle exec puma -t 5:5 -p 3000 -e ${RACK_ENV:-development}"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - redis
    volumes:
      - .:/covoiturage-libre
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - ELASTICSEARCH_URL=http://elastic:changeme@elasticsearch:9200
      - REDIS_URL=redis://redis:6379
```
